%Code generated by Najam(2K18/ELE/111) and Abdul Raheem(2K18/ELE/4)

%reading the image
NR=imread('Ballon.jpg');
figure
imshow(NR)
 
%extracting the image layers
yellow=NR(:,:,1);
green=NR(:,:,2);
red=NR(:,:,3);
 
%choice of pixel
d=impixel(NR);
 
%thersholding/Segmenting out the color, in our case "Yellow") 
output1=yellow>120 & green <200 & green> 80 & red>20;
figure
imshow(output1);
 
%image enhancement (filling holes to get much clearer image)
output2=imfill(output1,'holes');
output3=bwmorph(output2, 'dilate',5);
output3=imfill(output3, 'holes');
figure
imshow(output3);
 
%highlighting the image
imgBoth=imoverlay(NR,output3,'black');
figure
imshow(imgBoth);



 
